# Generated by Django 4.1.5 on 2023-06-05 08:26

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_supportticketv2_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketv2',
            name='ticket_attachments',
            field=models.FileField(blank=True, null=True, upload_to='support_ticket/support/', validators=[utils.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='solution_attachments',
            field=models.FileField(blank=True, null=True, upload_to='support_resolutions/resolutions/', validators=[utils.validators.validate_file_size]),
        ),
    ]
