# Generated by Django 4.1.5 on 2023-06-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0004_supportticketv2_ticket_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticketv2',
            name='status',
            field=models.CharField(choices=[('open', 'open'), ('hold', 'hold'), ('closed', 'closed')], default='closed', max_length=255),
        ),
    ]
