# Generated by Django 4.1.5 on 2023-06-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datahub', '0040_alter_datasetv2_name_alter_policy_description_and_more'),
        ('participant', '0005_supportticketv2_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportticketv2',
            old_name='ticket_attachments',
            new_name='ticket_attachment',
        ),
        migrations.AlterField(
            model_name='resolution',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participant.supportticketv2'),
        ),
        migrations.AlterField(
            model_name='supportticketv2',
            name='user_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datahub.userorganizationmap'),
        ),
    ]
