version: '3'

services:
  datahub-be:
    # restart: always
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
       python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000" 
    image: farmstack/celery_new1:restapi
    volumes:
      - /Users/ugesh/PycharmProjects/datahub-api/core/settings.py:/datahub/core/settings.py
      - /Users/ugesh/PycharmProjects/datahub-api/celery_app/tasks.py:/datahub/core/tasks.py
      - /Users/ugesh/PycharmProjects/datahub-api/celery_app/celery.py:/datahub/core/celery.py
    # container_name: datahub-be
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      SENDGRID_API_KEY: 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
      EMAIL_HOST_USER: varunramesh.07@gmail.com
    # links:
    #   - db:db
    networks:
      - postgresql-network
  # db:
  #   image: postgres
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - "POSTGRES_HOST_AUTH_METHOD=trust"
  #   hostname: postgres
  #   ports:
  #     - '5432:5432'
  #   networks:
  #     - postgresql-network
  # celeryworker:
  #   build:
  #     context: .
  #     dockerfile: docker-celery
  #   depends_on:
  #     - redis
  #   networks:
  #     - postgresql-network

  # celery-beat:
  #   build: .
  #   command: celery -A core beat --loglevel=info
  #   # Replace 'your_project_name' with your actual Django project name
  #   depends_on:
  #     - redis
  #   # Other configuration for Celery Beat
  #   networks:
  #     - postgresql-network

  celery-worker2:
    build:
      context: .
      dockerfile: docker-celery
    # volumes:
    #   - /Users/ugesh/PycharmProjects/datahub-api/core/settings.py:/datahub/core/settings.py
    #   - /Users/ugesh/PycharmProjects/datahub-api/core/tasks.py:/datahub/core/tasks.py
    #   - /Users/ugesh/PycharmProjects/datahub-api/core/celery.py:/datahub/core/celery.py
    command: celery -A core worker --loglevel=info
    # Replace 'your_project_name' with your actual Django project name
    # Make sure to have necessary configurations and environment variables
    networks:
      - postgresql-network

  # celery-flower:
  #   image: farmstack/celery_new1:restapi
  #   volumes:
  #     - /Users/ugesh/PycharmProjects/datahub-api/core/settings.py:/datahub/core/settings.py
  #     - /Users/ugesh/PycharmProjects/datahub-api/core/tasks.py:/datahub/core/tasks.py
  #     - /Users/ugesh/PycharmProjects/datahub-api/core/celery.py:/datahub/core/celery.py
  #   command: celery -A core flower
  #   # Replace 'your_project_name' with your actual Django project name
  #   # Make sure to have necessary configurations and environment variables
  #   networks:
  #     - postgresql-network
  #   ports:
  #     - "5555:5555"

  redis:
    container_name: redis_server
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - postgresql-network
  # worker_flower:
  #   container_name: redis_server
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - postgresql-network

volumes:
  db_data:
    driver: local
  redis_data:


networks:
  postgresql-network:
    driver: bridge
